### ISSUE TITLE
Freerasp causes error with SharedPreferences at start similar to #112

### ISSUE THREAD

**Issue by rakesh0689** [talsec/Free-RASP-Flutter#120]
**Describe the bug**
Freerasp causes error with SharedPreferences at startup and application does not detect root / hook etc..

**To Reproduce**
Similar to what is described in #112 

**Expected behavior**
Freerasp is supposed to detect root / hooks etc. but since the issue is happening the user is able to run the app on rooted device. But the is not coming every time sometimes when app is removed from memory and opened again Freerasp sometimes detects root sometimes this error comes. ALso when app is hot restarted while in debug mode then this issue is not there.

**Screenshots**
W/SharedPreferencesImpl(19382): Cannot read /data/user/0/com.sib.mHRMS.dev/shared_prefs/LPt63jFXmgP2hitXSjTyIScRrUsA7cK8RSCVk26.xml
W/SharedPreferencesImpl(19382): org.xmlpull.v1.XmlPullParserException: Unexpected end of document
W/SharedPreferencesImpl(19382): 	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1550)
W/SharedPreferencesImpl(19382): 	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:971)
W/SharedPreferencesImpl(19382): 	at android.app.SharedPreferencesImpl.loadFromDisk(SharedPreferencesImpl.java:179)
W/SharedPreferencesImpl(19382): 	at android.app.SharedPreferencesImpl.lambda$startLoadFromDisk$0(SharedPreferencesImpl.java:149)
W/SharedPreferencesImpl(19382): 	at android.app.SharedPreferencesImpl.$r8$lambda$gCIQI__z13DI5jNIqnAnYLWLcMc(Unknown Source:0)
W/SharedPreferencesImpl(19382): 	at android.app.SharedPreferencesImpl$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
W/SharedPreferencesImpl(19382): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
W/SharedPreferencesImpl(19382): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
W/SharedPreferencesImpl(19382): 	at java.lang.Thread.run(Thread.java:1012)
W/Sensors (19382): Cannot get virtualdevice_native service
D/nativeloader(19382): Load /data/app/~~PdqQLLHtN6sj7pn7zDNTBg==/com.sib.mHRMS.dev-BURVz3QSxsk6rEYBNw8ZkQ==/base.apk!/lib/arm64-v8a/libsecurity.so using ns clns-5 from class loader (caller=<unknown>): ok

**Please complete the following information:**
 - Device: Samsung Galaxy S10 on Lineage OS and rooted using Magisk Module + LSPosed installed
 - OS version: Android 14 (Lineage OS)
 - Version of freeRASP: 6.6.0

Additional context
This error only occurs at the execution of this line "await Talsec.instance.start(config);"
I don't use SharedPreferences in my project
Sample of callback implemented:
         onAppIntegrity: () {
            isAppSecure.value = false;
            threatText.value =
                'Package tamper detected. Cannot proceed further !!';
          },

Any help would be greatly helpful. This is happening in Production build as well.

**Comment by msikyna** [comment]
Hello @rakesh0689 ,

thank you for reporting the issue, we will look at it.

Kind regards,
Talsec team

**Comment by AwaisQazii** [comment]
Hi @msikyna ,
  did you able to resolve this issue?

**Comment by urvesh-sm** [comment]
Hi @msikyna ,

Is there an update or solution for this? We are facing the same issue:
```
W/SharedPreferencesImpl( 7547): Cannot read /data/user/0/<packageId>/shared_prefs/LpT8W5aFMBRoU0MCvKl3hGlhBEYszkisbY8DLEsylFvG.xml
W/SharedPreferencesImpl( 7547): org.xmlpull.v1.XmlPullParserException: Unexpected end of document
W/SharedPreferencesImpl( 7547): 	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1550)
W/SharedPreferencesImpl( 7547): 	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:971)
W/SharedPreferencesImpl( 7547): 	at android.app.SharedPreferencesImpl.loadFromDisk(SharedPreferencesImpl.java:179)
W/SharedPreferencesImpl( 7547): 	at android.app.SharedPreferencesImpl.lambda$startLoadFromDisk$0(SharedPreferencesImpl.java:149)
W/SharedPreferencesImpl( 7547): 	at android.app.SharedPreferencesImpl.$r8$lambda$gCIQI__z13DI5jNIqnAnYLWLcMc(Unknown Source:0)
W/SharedPreferencesImpl( 7547): 	at android.app.SharedPreferencesImpl$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
W/SharedPreferencesImpl( 7547): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
W/SharedPreferencesImpl( 7547): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
W/SharedPreferencesImpl( 7547): 	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by yardexx** [comment]
Hello.

We are aware of this issue - it is caused by an internal component. It does not affect detection or performance. We have plans in place to resolve it.

Jaroslav from Talsec

**Comment by AwaisQazii** [comment]
Any Updates?

**Comment by msikyna** [comment]
https://github.com/talsec/Free-RASP-Flutter/issues/147

**Comment by vallerydelexy** [comment]
> Hello.
> 
> We are aware of this issue - it is caused by an internal component. It does not affect detection or performance. We have plans in place to resolve it.
> 
> Jaroslav from Talsec

hey, any update on this?
im still facing this issue on the latest version freerasp: ^6.10.0

**Comment by SirionRazzer** [comment]
Hi @fajarainul ,
This is not related to certificates. The SharedPreferences rare exceptions is already resolved.
