### ISSUE TITLE
Talsec causes app crash at startup

### ISSUE THREAD

**Issue by robban112** [talsec/Free-RASP-Flutter#21]
Hi,

we're having some issues with talsec as it is causing a crash at startup. Running the app in debug mode connected to the computer works fine, however, when building an apk and installing it a crash occurs with this error message:

Fatal Exception: java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String[] R0.a.g() (tried Java_R0_a_g and Java_R0_a_g__)
       at com.aheaditec.talsec_security.security.Natives.b(Natives.java)
       at com.aheaditec.talsec_security.security.Natives.d(Natives.java)
       at a.a.b.c.j.d.a(d.java:2)
       at a.a.b.c.j.c.b(c.java:2)
       at a.a.b.c.j.c.g(c.java:2)
       at a.a.b.c.j.c.$r8$lambda$48_804VhmcnRxfa6ZEcEZfh8_W8(c.java:2)
       at a.a.b.c.k.a.a(a.java:1)
       at a.a.b.c.j.c.d(c.java:1)
       at a.a.b.c.j.c.a(c.java)
       at a.a.b.c.k.g.a(g.java:29)
       at o.g$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:26)
       at java.lang.Thread.run(Thread.java:920)

One thing worth mentioning is that we use two different product flavors, and the issue seems to have occured after this implementation. We're also using different main files for the different flavors (lib/main_prod.dart, lib/main_dev.dart).

Any idea how to solve this issue?

**Comment by talsec-app** [comment]
Hello @robban112 , we will look at the issue and get back to you promptly.

Kind regards,
Talsec team

**Comment by robban112** [comment]
Thanks for the quick reply,

The issue was solved by adding a proguard-rules.pro file with this content:

-keepclasseswithmembernames,includedescriptorclasses class * {
    native <methods>;
}

If there are others facing this issue this might be of help

**Comment by talsec-app** [comment]
Hello @robban112

We were able to replicate and also apply your solution to the issue. README trobleshooting section will be updated accordingly.

Kind regards,
Talsec Team
