### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference

### ISSUE THREAD

**Issue by olexale** [talsec/Free-RASP-Flutter#40]
Can not reproduce this NPE locally. It happened on Android 11 & 12 for a few users.

```ruby
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
       at com.aheaditec.talsec.security.k1.e(SourceFile:10)
       at com.aheaditec.talsec.security.k1.g(SourceFile:10)
       at com.aheaditec.talsec.security.k1.$r8$lambda$llnNtpFpp0MEWB0RhtqrUDAuXaY(SourceFile)
       at com.aheaditec.talsec.security.k1$$InternalSyntheticLambda$1$fa5e170b00cd179a7b8aca1202b01d848d1d21c7b74151c65d5fdb6fc8039d8d$0.run(k1.java:4)
       at com.aheaditec.talsec.security.m1.a(SourceFile:25)
       at com.aheaditec.talsec.security.k1.d(SourceFile:1)
       at com.aheaditec.talsec.security.k1.a(SourceFile:2)
       at com.aheaditec.talsec.security.s1.d(SourceFile:3)
       at com.aheaditec.talsec.security.s1.$r8$lambda$DEiFfqTS15ahlVEiavfeOkwe6KI(SourceFile)
       at com.aheaditec.talsec.security.s1$$InternalSyntheticLambda$1$70e647751427081963304fa1c05aa9eb4e5c1786996cb107c2e81f823c0c2dce$0.run(s1.java:4)
       at java.lang.Thread.run(Thread.java:923)
```

**Comment by yardexx** [comment]
Hi @olexale 

Thank you for report. We will look into it.

Kind regards,
Jaroslav from Talsec Team

**Comment by talsec-app** [comment]
Hello, 
we are actively looking into the issue. We apologize for the delay due to the holidays.

Kind regards,
Talsec team

**Comment by msikyna** [comment]
Hello,
we have found the issue. It will be fixed in the next release, which will be delivered soon.

Kind regards,
Matúš from Talsec team

**Comment by yardexx** [comment]
Hello everyone!

New version of freeRASP have been released. New version should fix this issue. 

Jaroslav from Talsec Team
