### ISSUE TITLE
bug: UnsatisfiedLinkError in Flutter release version

### ISSUE THREAD

**Issue by philmayes** [talsec/Free-RASP-Flutter#59]
Release version on Play Store crashes with stack trace:
```
Exception java.lang.UnsatisfiedLinkError:
  at com.aheaditec.talsec_security.security.Natives.b (Natives.java)
  at com.aheaditec.talsec_security.security.Natives.d (Natives.java)
  at com.aheaditec.talsec.security.p1.a (p1.java:7)
  at com.aheaditec.talsec.security.o1.b (o1.java:7)
  at com.aheaditec.talsec.security.o1.g (o1.java:7)
  at com.aheaditec.talsec.security.o1.lambda$pQuqSPVg98SPzityJyeCuWmt-cM (o1.java:7)
  at com.aheaditec.talsec.security.-$$Lambda$o1$pQuqSPVg98SPzityJyeCuWmt-cM.run (-.java:7)
  at com.aheaditec.talsec.security.b.a (b.java)
  at com.aheaditec.talsec.security.o1.d (o1.java:1)
  at com.aheaditec.talsec.security.o1.a (o1.java:1)
  at com.aheaditec.talsec.security.z1.d (z1.java:1)
  at com.aheaditec.talsec.security.z1.lambda$R8aaFX36gDYmbo_QFUzjIfRwELs (z1.java:1)
  at com.aheaditec.talsec.security.-$$Lambda$z1$R8aaFX36gDYmbo_QFUzjIfRwELs.run (-.java:1)
  at java.lang.Thread.run (Thread.java:1012)
```
Google reports these crashes as being on samsung p3q & samsung r8q and it also fails locally on Pixel 7 Pro.

I tried using the Free-RASP-Community suggestion
```
dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation "com.google.android.gms:play-services-ads:21.4.0"
    implementation "com.android.billingclient:billing:5.1.0"
    // Talsec Release
    releaseImplementation 'com.aheaditec.talsec.security:TalsecSecurity-Community-Flutter:4.0.0-release'
    // Talsec Debug
    // implementation 'com.aheaditec.talsec.security:TalsecSecurity-Community-Flutter:4.0.0-dev'
}
```
but (probably not surprising) this gave me
```
Launching lib\main.dart on Pixel 7 Pro in release mode...
√  Built build\app\outputs\flutter-apk\app-release.apk (15.0MB).
E/AndroidRuntime(11270): FATAL EXCEPTION: Thread-5
E/AndroidRuntime(11270): Process: app.fourfit.fourfit, PID: 11270
E/AndroidRuntime(11270): java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String[] e.a.c.a.a.f() (tried Java_e_a_c_a_a_f and Java_e_a_c_a_a_f__)
E/AndroidRuntime(11270): 	at e.a.c.a.a.f(Native Method)
E/AndroidRuntime(11270): 	at e.a.c.a.a.k(Unknown Source:0)
E/AndroidRuntime(11270): 	at e.a.b.a.e.run(:7)
E/AndroidRuntime(11270): 	at e.a.b.a.p.c(Unknown Source:8)
E/AndroidRuntime(11270): 	at e.a.b.a.i0.b(:1)
E/AndroidRuntime(11270): 	at e.a.b.a.h.run(:1)
E/AndroidRuntime(11270): 	at java.lang.Thread.run(Thread.java:1012)
I/flutter (11270): _loadLocal result: false
```
I'm running:
* Flutter 3.7.12
* Dart 2.19.6
* freerasp: ^4.0.0
* VS Code

Everything works fine in debug AND profile modes. Thanks for any help :-)

**Comment by msikyna** [comment]
Hello @philmayes ,

we will look at the issue. Thank you for reporting it.

Kind regards,
Talsec team

**Comment by yardexx** [comment]
Hello.

Could you provide your proguard rules which are used in given project? If don't want to share them here, you can send them to support@talsec.app

Kind regards,
Jaroslav from Talsec Team

**Comment by msikyna** [comment]
Hello @philmayes ,
we have inspected a similar issue and provided a partial solution and suggested a few more solutions, which needs to be tested. You can check it out in this issue: https://github.com/talsec/Free-RASP-Android/issues/18

Kind regards,
Talsec team

**Comment by yardexx** [comment]
Closed as resolved.

If issue persists, please reopen this issue.
