### ISSUE TITLE
DeadObjectException on some Android 6 devices

### ISSUE THREAD

**Issue by kreativityapps** [talsec/Free-RASP-Flutter#84]
**Describe the bug**
Crashes on some Android 6 devices.

**To Reproduce**
Can't reproduce, saw it only in production crash logs.

**Expected behavior**
It shouldn't crash.

**Screenshots**
No screenshots

**Please complete the following information:**
 - Device: Samsung Galaxy J3 Emerge, J2 Prime, J7, S6 Edge, S5, A7, LGE X Max
 - OS version: only on Android 6
 - Version of freeRASP: 6.1.0

**Additional context**
Crash log:

```Fatal Exception: java.lang.RuntimeException
Package manager has died
Fatal Exception: java.lang.RuntimeException: Package manager has died
       at android.app.ApplicationPackageManager.queryIntentActivitiesAsUser(ApplicationPackageManager.java:659)
       at android.app.ApplicationPackageManager.queryIntentActivities(ApplicationPackageManager.java:645)
       at com.aheaditec.talsec.security.o1.a(o1.java)
       at com.aheaditec.talsec.security.o1.a(o1.java)
       at com.aheaditec.talsec.security.b.a(b.java)
       at com.aheaditec.talsec.security.o1.c(o1.java)
       at com.aheaditec.talsec.security.o1.a(o1.java)
       at com.aheaditec.talsec.security.a2.d(a2.java)
       at java.lang.Thread.run(Thread.java:818)
Caused by android.os.DeadObjectException
Transaction failed on small parcel; remote process probably died
Caused by android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
       at android.os.BinderProxy.transactNative(Binder.java)
       at android.os.BinderProxy.transact(Binder.java:503)
       at android.content.pm.IPackageManager$Stub$Proxy.queryIntentActivities(IPackageManager.java:3060)
       at android.app.ApplicationPackageManager.queryIntentActivitiesAsUser(ApplicationPackageManager.java:653)
       at android.app.ApplicationPackageManager.queryIntentActivities(ApplicationPackageManager.java:645)
       at com.aheaditec.talsec.security.o1.a(o1.java)
       at com.aheaditec.talsec.security.o1.a(o1.java)
       at com.aheaditec.talsec.security.b.a(b.java)
       at com.aheaditec.talsec.security.o1.c(o1.java)
       at com.aheaditec.talsec.security.o1.a(o1.java)
       at com.aheaditec.talsec.security.a2.d(a2.java)
       at java.lang.Thread.run(Thread.java:818)

**Comment by msikyna** [comment]
Hello @kreativityapps ,
thank you for reporting the issue. We will look at it.

Kind regards,
Talsec team

**Comment by MajdSallora** [comment]
same

**Comment by SirionRazzer** [comment]
This issue is fixed, it will be included in the next release.

**Comment by msikyna** [comment]
Hello @kreativityapps , @MajdSallora ,
a new version v6.3.0 has been released with the issue fixed. Thank you for reporting it!

Kind regards,
Talsec team
