### ISSUE TITLE
Build fails on Profile mode with FreeRASP

### ISSUE THREAD

**Issue by suleymancalikprb** [talsec/Free-RASP-Flutter#9]
While applicatiion build successfully on Debug and Release modes, it fails on Profile mode.

Here is console output.

```
Launching lib/main.dart on SM A115F in profile mode...
e: /Users/suleymancalik/Development/flutter/.pub-cache/hosted/pub.dartlang.org/freerasp-2.0.0/android/src/main/kotlin/com/aheaditec/freerasp/TalsecApp.kt: (4, 22): Unresolved reference: talsec_security
e: /Users/suleymancalik/Development/flutter/.pub-cache/hosted/pub.dartlang.org/freerasp-2.0.0/android/src/main/kotlin/com/aheaditec/freerasp/TalsecApp.kt: (5, 22): Unresolved reference: talsec_security
e: /Users/suleymancalik/Development/flutter/.pub-cache/hosted/pub.dartlang.org/freerasp-2.0.0/android/src/main/kotlin/com/aheaditec/freerasp/TalsecApp.kt: (6, 22): Unresolved reference: talsec_security
e: /Users/suleymancalik/Development/flutter/.pub-cache/hosted/pub.dartlang.org/freerasp-2.0.0/android/src/main/kotlin/com/aheaditec/freerasp/TalsecApp.kt: (10, 49): Unresolved reference: ThreatListener
e: /Users/suleymancalik/Development/flutter/.pub-cache/hosted/pub.dartlang.org/freerasp-2.0.0/android/src/main/kotlin/com/aheaditec/freerasp/TalsecApp.kt: (20, 22): Unresolved reference: TalsecConfig
e: /Users/suleymancalik/Development/flutter/.pub-cache/hosted/pub.dartlang.org/freerasp-2.0.0/android/src/main/kotlin/com/aheaditec/freerasp/TalsecApp.kt: (26, 9): Unresolved reference: ThreatListener
e: /Users/suleymancalik/Development/flutter/.pub-cache/hosted/pub.dartlang.org/freerasp-2.0.0/android/src/main/kotlin/com/aheaditec/freerasp/TalsecApp.kt: (27, 9): Unresolved reference: Talsec

e: /Users/suleymancalik/Development/flutter/.pub-cache/hosted/pub.dartlang.org/freerasp-2.0.0/android/src/main/kotlin/com/aheaditec/freerasp/TalsecApp.kt: (34, 5): 'onRootDetected' overrides nothing
e: /Users/suleymancalik/Development/flutter/.pub-cache/hosted/pub.dartlang.org/freerasp-2.0.0/android/src/main/kotlin/com/aheaditec/freerasp/TalsecApp.kt: (39, 5): 'onDebuggerDetected' overrides nothing
e: /Users/suleymancalik/Development/flutter/.pub-cache/hosted/pub.dartlang.org/freerasp-2.0.0/android/src/main/kotlin/com/aheaditec/freerasp/TalsecApp.kt: (43, 5): 'onEmulatorDetected' overrides nothing

e: /Users/suleymancalik/Development/flutter/.pub-cache/hosted/pub.dartlang.org/freerasp-2.0.0/android/src/main/kotlin/com/aheaditec/freerasp/TalsecApp.kt: (47, 5): 'onTamperDetected' overrides nothing
e: /Users/suleymancalik/Development/flutter/.pub-cache/hosted/pub.dartlang.org/freerasp-2.0.0/android/src/main/kotlin/com/aheaditec/freerasp/TalsecApp.kt: (51, 5): 'onHookDetected' overrides nothing

e: /Users/suleymancalik/Development/flutter/.pub-cache/hosted/pub.dartlang.org/freerasp-2.0.0/android/src/main/kotlin/com/aheaditec/freerasp/TalsecApp.kt: (55, 5): 'onDeviceBindingDetected' overrides nothing
e: /Users/suleymancalik/Development/flutter/.pub-cache/hosted/pub.dartlang.org/freerasp-2.0.0/android/src/main/kotlin/com/aheaditec/freerasp/TalsecApp.kt: (59, 5): 'onUntrustedInstallationSourceDetected' overrides nothing

FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':freerasp:compileProfileKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 57s
Exception: Gradle task assembleDevProfile failed with exit code 1
#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:400:9)
<asynchronous suspension>
#2      AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:179:5)
<asynchronous suspension>
#3      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:579:7)
<asynchronous suspension>
#4      FlutterDevice.runCold (package:flutter_tools/src/resident_runner.dart:501:33)
<asynchronous suspension>
#5      ColdRunner.run (package:flutter_tools/src/run_cold.dart:71:28)
<asynchronous suspension>
#6      AppDomain.launch.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:621:9)
<asynchronous suspension>
#7      AppDomain.launch (package:flutter_tools/src/commands/daemon.dart:619:5)
<asynchronous suspension>
#8      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:571:15)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#17     main (package:flutter_tools/executable.dart:94:3)
<asynchronous suspension>

Exited (sigterm)

```

**Comment by talsec-app** [comment]
Hello suleymancalikprb
Thank you for your report. We are investigating the issue and looking for solution.
Talsec Team

**Comment by talsec-app** [comment]
We managed to replicate and solve issue. Issue will fixed in the next version of freeRASP.
In the meantime, you can solve fix problem by manually changing dependencies in freeRASP:
(For Android Studio):
In project tab choose **External Libraries** -> **Flutter Plugins** -> **freerasp-2.0.0** -> **android** -> **build.gradle**
In **build.gradle** in **dependcies** part, edit current implementations to:

```gradle
dependencies {
    // Some other dependecies ...
   
    // Talsec Release
    releaseImplementation 'com.aheaditec.talsec.security:TalsecSecurity-Community-Flutter:3.3.2-release'

    // Talsec Debug - EDIT THIS LINE BELOW
    implementation 'com.aheaditec.talsec.security:TalsecSecurity-Community-Flutter:3.3.2-dev'
}
```
If Android Studio shows dialog box, choose to edit anyway. Now, dev version of freeRASP will run on profile build.

If you don't have Android Studio, you can open build.gradle in any text editor and edit it there. Path to the library is 
```
your_flutter_sdk_path/flutter/.pub_cache/hosted/pub.dartlang.org/freerasp-2.0.0/android/build.gradle
```
Talsec Team

**Comment by suleymancalikprb** [comment]
Thank you, I'll try.
